/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransitosRouteImport } from './routes/_authenticated/transitos'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMomentoRouteImport } from './routes/_authenticated/momento'
import { Route as AuthenticatedMapasRouteImport } from './routes/_authenticated/mapas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCompatibilidadeRouteImport } from './routes/_authenticated/compatibilidade'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMapasNovoRouteImport } from './routes/_authenticated/mapas.novo'
import { Route as AuthenticatedMapasIdRouteImport } from './routes/_authenticated/mapas.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransitosRoute = AuthenticatedTransitosRouteImport.update({
  id: '/transitos',
  path: '/transitos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMomentoRoute = AuthenticatedMomentoRouteImport.update({
  id: '/momento',
  path: '/momento',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapasRoute = AuthenticatedMapasRouteImport.update({
  id: '/mapas',
  path: '/mapas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompatibilidadeRoute =
  AuthenticatedCompatibilidadeRouteImport.update({
    id: '/compatibilidade',
    path: '/compatibilidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapasNovoRoute = AuthenticatedMapasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedMapasRoute,
} as any)
const AuthenticatedMapasIdRoute = AuthenticatedMapasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMapasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compatibilidade': typeof AuthenticatedCompatibilidadeRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mapas': typeof AuthenticatedMapasRouteWithChildren
  '/momento': typeof AuthenticatedMomentoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/transitos': typeof AuthenticatedTransitosRoute
  '/mapas/$id': typeof AuthenticatedMapasIdRoute
  '/mapas/novo': typeof AuthenticatedMapasNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compatibilidade': typeof AuthenticatedCompatibilidadeRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mapas': typeof AuthenticatedMapasRouteWithChildren
  '/momento': typeof AuthenticatedMomentoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/transitos': typeof AuthenticatedTransitosRoute
  '/mapas/$id': typeof AuthenticatedMapasIdRoute
  '/mapas/novo': typeof AuthenticatedMapasNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/compatibilidade': typeof AuthenticatedCompatibilidadeRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mapas': typeof AuthenticatedMapasRouteWithChildren
  '/_authenticated/momento': typeof AuthenticatedMomentoRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/transitos': typeof AuthenticatedTransitosRoute
  '/_authenticated/mapas/$id': typeof AuthenticatedMapasIdRoute
  '/_authenticated/mapas/novo': typeof AuthenticatedMapasNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/compatibilidade'
    | '/configuracoes'
    | '/dashboard'
    | '/mapas'
    | '/momento'
    | '/onboarding'
    | '/premium'
    | '/transitos'
    | '/mapas/$id'
    | '/mapas/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/compatibilidade'
    | '/configuracoes'
    | '/dashboard'
    | '/mapas'
    | '/momento'
    | '/onboarding'
    | '/premium'
    | '/transitos'
    | '/mapas/$id'
    | '/mapas/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/compatibilidade'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/mapas'
    | '/_authenticated/momento'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/transitos'
    | '/_authenticated/mapas/$id'
    | '/_authenticated/mapas/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transitos': {
      id: '/_authenticated/transitos'
      path: '/transitos'
      fullPath: '/transitos'
      preLoaderRoute: typeof AuthenticatedTransitosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/momento': {
      id: '/_authenticated/momento'
      path: '/momento'
      fullPath: '/momento'
      preLoaderRoute: typeof AuthenticatedMomentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapas': {
      id: '/_authenticated/mapas'
      path: '/mapas'
      fullPath: '/mapas'
      preLoaderRoute: typeof AuthenticatedMapasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compatibilidade': {
      id: '/_authenticated/compatibilidade'
      path: '/compatibilidade'
      fullPath: '/compatibilidade'
      preLoaderRoute: typeof AuthenticatedCompatibilidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapas/novo': {
      id: '/_authenticated/mapas/novo'
      path: '/novo'
      fullPath: '/mapas/novo'
      preLoaderRoute: typeof AuthenticatedMapasNovoRouteImport
      parentRoute: typeof AuthenticatedMapasRoute
    }
    '/_authenticated/mapas/$id': {
      id: '/_authenticated/mapas/$id'
      path: '/$id'
      fullPath: '/mapas/$id'
      preLoaderRoute: typeof AuthenticatedMapasIdRouteImport
      parentRoute: typeof AuthenticatedMapasRoute
    }
  }
}

interface AuthenticatedMapasRouteChildren {
  AuthenticatedMapasIdRoute: typeof AuthenticatedMapasIdRoute
  AuthenticatedMapasNovoRoute: typeof AuthenticatedMapasNovoRoute
}

const AuthenticatedMapasRouteChildren: AuthenticatedMapasRouteChildren = {
  AuthenticatedMapasIdRoute: AuthenticatedMapasIdRoute,
  AuthenticatedMapasNovoRoute: AuthenticatedMapasNovoRoute,
}

const AuthenticatedMapasRouteWithChildren =
  AuthenticatedMapasRoute._addFileChildren(AuthenticatedMapasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompatibilidadeRoute: typeof AuthenticatedCompatibilidadeRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMapasRoute: typeof AuthenticatedMapasRouteWithChildren
  AuthenticatedMomentoRoute: typeof AuthenticatedMomentoRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedTransitosRoute: typeof AuthenticatedTransitosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompatibilidadeRoute: AuthenticatedCompatibilidadeRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMapasRoute: AuthenticatedMapasRouteWithChildren,
  AuthenticatedMomentoRoute: AuthenticatedMomentoRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedTransitosRoute: AuthenticatedTransitosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
