/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTransitosRouteImport } from './routes/_authenticated/transitos'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMomentoRouteImport } from './routes/_authenticated/momento'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCompatibilidadeRouteImport } from './routes/_authenticated/compatibilidade'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMapasIndexRouteImport } from './routes/_authenticated/mapas.index'
import { Route as AuthenticatedMapasNovoRouteImport } from './routes/_authenticated/mapas.novo'
import { Route as AuthenticatedMapasIdRouteImport } from './routes/_authenticated/mapas.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTransitosRoute = AuthenticatedTransitosRouteImport.update({
  id: '/transitos',
  path: '/transitos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMomentoRoute = AuthenticatedMomentoRouteImport.update({
  id: '/momento',
  path: '/momento',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompatibilidadeRoute =
  AuthenticatedCompatibilidadeRouteImport.update({
    id: '/compatibilidade',
    path: '/compatibilidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapasIndexRoute = AuthenticatedMapasIndexRouteImport.update({
  id: '/mapas/',
  path: '/mapas/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapasNovoRoute = AuthenticatedMapasNovoRouteImport.update({
  id: '/mapas/novo',
  path: '/mapas/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapasIdRoute = AuthenticatedMapasIdRouteImport.update({
  id: '/mapas/$id',
  path: '/mapas/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compatibilidade': typeof AuthenticatedCompatibilidadeRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/momento': typeof AuthenticatedMomentoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/transitos': typeof AuthenticatedTransitosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mapas/$id': typeof AuthenticatedMapasIdRoute
  '/mapas/novo': typeof AuthenticatedMapasNovoRoute
  '/mapas/': typeof AuthenticatedMapasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compatibilidade': typeof AuthenticatedCompatibilidadeRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/momento': typeof AuthenticatedMomentoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/transitos': typeof AuthenticatedTransitosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mapas/$id': typeof AuthenticatedMapasIdRoute
  '/mapas/novo': typeof AuthenticatedMapasNovoRoute
  '/mapas': typeof AuthenticatedMapasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/compatibilidade': typeof AuthenticatedCompatibilidadeRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/momento': typeof AuthenticatedMomentoRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/transitos': typeof AuthenticatedTransitosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/mapas/$id': typeof AuthenticatedMapasIdRoute
  '/_authenticated/mapas/novo': typeof AuthenticatedMapasNovoRoute
  '/_authenticated/mapas/': typeof AuthenticatedMapasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/compatibilidade'
    | '/configuracoes'
    | '/dashboard'
    | '/momento'
    | '/onboarding'
    | '/premium'
    | '/transitos'
    | '/auth/callback'
    | '/mapas/$id'
    | '/mapas/novo'
    | '/mapas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/compatibilidade'
    | '/configuracoes'
    | '/dashboard'
    | '/momento'
    | '/onboarding'
    | '/premium'
    | '/transitos'
    | '/auth/callback'
    | '/mapas/$id'
    | '/mapas/novo'
    | '/mapas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/compatibilidade'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/momento'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/transitos'
    | '/auth/callback'
    | '/_authenticated/mapas/$id'
    | '/_authenticated/mapas/novo'
    | '/_authenticated/mapas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/transitos': {
      id: '/_authenticated/transitos'
      path: '/transitos'
      fullPath: '/transitos'
      preLoaderRoute: typeof AuthenticatedTransitosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/momento': {
      id: '/_authenticated/momento'
      path: '/momento'
      fullPath: '/momento'
      preLoaderRoute: typeof AuthenticatedMomentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compatibilidade': {
      id: '/_authenticated/compatibilidade'
      path: '/compatibilidade'
      fullPath: '/compatibilidade'
      preLoaderRoute: typeof AuthenticatedCompatibilidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapas/': {
      id: '/_authenticated/mapas/'
      path: '/mapas'
      fullPath: '/mapas/'
      preLoaderRoute: typeof AuthenticatedMapasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapas/novo': {
      id: '/_authenticated/mapas/novo'
      path: '/mapas/novo'
      fullPath: '/mapas/novo'
      preLoaderRoute: typeof AuthenticatedMapasNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapas/$id': {
      id: '/_authenticated/mapas/$id'
      path: '/mapas/$id'
      fullPath: '/mapas/$id'
      preLoaderRoute: typeof AuthenticatedMapasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompatibilidadeRoute: typeof AuthenticatedCompatibilidadeRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMomentoRoute: typeof AuthenticatedMomentoRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedTransitosRoute: typeof AuthenticatedTransitosRoute
  AuthenticatedMapasIdRoute: typeof AuthenticatedMapasIdRoute
  AuthenticatedMapasNovoRoute: typeof AuthenticatedMapasNovoRoute
  AuthenticatedMapasIndexRoute: typeof AuthenticatedMapasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompatibilidadeRoute: AuthenticatedCompatibilidadeRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMomentoRoute: AuthenticatedMomentoRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedTransitosRoute: AuthenticatedTransitosRoute,
  AuthenticatedMapasIdRoute: AuthenticatedMapasIdRoute,
  AuthenticatedMapasNovoRoute: AuthenticatedMapasNovoRoute,
  AuthenticatedMapasIndexRoute: AuthenticatedMapasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
